// Constant for reducers and action.
const types = {
  INIT_AUTH: 'INIT_AUTH',
  VALUE_CHANGE: 'VALUE_CHANGE',
  FORM_ERROR: 'FORM_ERROR',
  TOPIC_SUBSCRIPTION_LOADING: 'TOPIC_SUBSCRIPTION_LOADING',
  TOPIC_SUBSCRIPTION_SUCCESS: 'TOPIC_SUBSCRIPTION_SUCCESS',
  TOPIC_SUBSCRIPTION_FAIL: 'TOPIC_SUBSCRIPTION_FAIL',
  NOTIFICATION_RECEIVED: 'NOTIFICATION_RECEIVED',
  GET_HISTORICAL_DATA: 'GET_HISTORICAL_DATA',
  GET_HISTORICAL_DATA_SUCCESS: 'GET_HISTORICAL_DATA_SUCCESS',
  GET_SUBSCRIBED_TOPICS: 'GET_SUBSCRIBED_TOPICS',
  GET_SUBSCRIBED_TOPICS_SUCCESS: 'GET_SUBSCRIBED_TOPICS_SUCCESS'
};

export default types;
