# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Grillo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Firebase/Core', '~> 5.9.0'
  pod 'Firebase/Auth', '~> 5.9.0'
  pod 'Firebase/Firestore', '~> 5.9.0'
  pod 'Firebase/Messaging', '~> 5.9.0'
  pod 'GoogleSignIn'
  pod 'TwitterKit', '~> 3.3.0'
  pod 'FBSDKCoreKit' 
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit' 
  # Pods for Grillo

  target 'Grillo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GrilloTests' do
    inherit! :search_paths
    # Pods for testing
  end

end